config/routes.rb
Rails.application.routes.draw do
  root to: "recipes#new"
  resources :recipes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
require 'ruby/openai'

class RecipesController < ApplicationController
  def show
    temp_recipe = Recipe.find(params[:id])
    
    openai = OpenAI::Client.new(access_token: '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')
    # prompt = "Give me a native recipe title, measured ingredients, and numbered instructions of a distinct '#{temp_recipe.origin}' cuisine
    #           that uses the following ingredients: '#{temp_recipe.ingredients}'. The returned recipe should be in JSON format with 
    #           three parameters 'title' and 'ingredients' and 'instructions' "
    # prompt = "Give me the recipe to a '#{temp_recipe.origin}' dish with '#{temp_recipe.ingredients}'. The returned recipe should be in JSON format with 
    # #           three parameters 'title' and 'ingredients' and 'instructions'"
    prompt = "Give me a '#{temp_recipe.origin}' dish with '#{temp_recipe.ingredients}'. Avoid making up dishes or lying. The returned recipe should be in JSON format with 
    three parameters 'title' (which is the dish's native name) and 'ingredients' and 'instructions'"
    response = openai.completions(
      parameters: {
        model: "text-davinci-003",
        prompt: prompt,
        temperature: 0.1,
        max_tokens: 500,
     }
    )
    json_response = JSON.parse(response['choices'][0]['text'].lstrip)
    
    temp_recipe.title = json_response["title"]
    temp_recipe.requirements = json_response["ingredients"].join("\n")
    temp_recipe.instructions = json_response["instructions"].join("\n")

    @recipe = temp_recipe
  end

  def new
    @recipe=Recipe.new
  end

  def create
    @recipe = Recipe.new(ingredients: params[:recipe][:ingredients], origin: params[:recipe][:origin],
                         title: "...", instructions: "...", requirements: "...")
    if @recipe.save
      redirect_to @recipe
    else
      render :new, status: :unprocessable_entity
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mix It Up</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<!DOCTYPE html>
<html>
  <head>

    <style>
    p {
    margin: 10px 10px 10px 10px;
    }
    </style>
    <title>
      Mixitup!
    </title>
    <link href='https://fonts.googleapis.com/css?family=Inter' rel='stylesheet'>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@800&amp;display=swap" rel="stylesheet">
    <style>
              body {
                  background-image: linear-gradient(#000000,#CACACA,#FFFFFF);
                  margin: 0px;
              }
              .container{
                  display: inline-block;
                  width: 100%;
                  flex-direction: column;
              }
              .headerContainer {
                  position: relative;
                  align-items: center;
                  justify-content: center;
              }
              .inContainer {
                  display: flex;
                  flex-direction: row;
              }
              .spectrum {
                  z-index: -1;
                  position: absolute;
              }
              .titleBubble {
                  width: fit-content;
                  padding-left: 40px;
                  padding-right: 40px;
                  padding-top: 20px;
                  padding-bottom: 20px;
                  background-color:#00000030;
                  border-radius: 50px;
                  color:white;
                  font-size: 75px;
                  font-weight:800;
                  align-items: center;
                  justify-content: center;
                  font-family: 'Inter';
                  backdrop-filter: blur(20px);
                  z-index: 1;
                  position: relative;
                  margin: 20px auto 20px auto;
              }
              .module {
                  height: 400px;
                  width: 33.33%
              }
              .test {
                  outline-style: solid;
                  outline-color: green;
                  outline-width: 1px;
              }
    </style>
  </head>
  <body>
    <div class="container test">
      <div class="headerContainer test">
        <div class="spectrum test">
          <div id="trapezoid"></div><!-- <svg width="1436" height="180" viewBox="0 0 1436 180" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M959 180H479L654.5 -1H782.5L959 180Z" fill="#FED700"/>
                            <path d="M959 180H479L654.5 -1H782.5L959 180Z" fill="black" fill-opacity="0.2"/>
                            <path d="M526 -0.432602L0 180L478.5 179.433L654 -1L526 -0.432602Z" fill="#FE218B"/>
                            <path d="M526 -0.432602L0 180L478.5 179.433L654 -1L526 -0.432602Z" fill="black" fill-opacity="0.2"/>
                            <path d="M910.402 -1L1436 180H959.365L783 -1H910.402Z" fill="#21B0FE"/>
                            <path d="M910.402 -1L1436 180H959.365L783 -1H910.402Z" fill="black" fill-opacity="0.2"/>
                        </svg> -->
        </div>
        <div class="titleBubble test">
          <div class="titleText test">
            MIX IT UP!
          </div>
        </div>
      </div><%= form_with model: @recipe do |form| %>
      <div>
        <div class="inContainer test">
          <div style="background-color: #FE218B" class="module test">
            <p>
              I have the following
            </p><%= form.label :ingredients%><br>
            <%= form.text_area :ingredients %>
          </div>
          <div style="background-color: #FED700" class="module test">
            <p>
              I want something from Here.
            </p><%= form.label :origin %><br>
            <%= form.text_area :origin %>
          </div>
          <div style="background-color: #21B0FE" class="module test">
            <p>
              Here is what we suggest!
            </p><%= form.submit %>
          </div>
        </div><%end %>
      </div>
    </div>
  </body>
</html>

app/views/recipes/new.html.erb
<!DOCTYPE html>
<html>
    <head>

    <style>
    p {
    margin: 10px 10px 10px 10px;
    }
    </style>
    <title>
        Mix It Up!
    </title>
    <link href='https://fonts.googleapis.com/css?family=Inter' rel='stylesheet'>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@800&amp;display=swap" rel="stylesheet">
    <style>
            body {
                background-image: linear-gradient(#000000,#CACACA,#FFFFFF);
                margin: 0px;
            }
            .container{
                display: inline-block;
                width: 100%;
                flex-direction: column;
                margin: 0px;
            }
            .headerContainer {
                position: relative;
                align-items: center;
                justify-content: center;
            }
            .inContainer {
                display: flex;
                flex-direction: row;
                font-family: 'Inter';
            }
            .spectrum {
                top: 20px;
                width: 100%;
                z-index: -1;
                height: 100%;
                position: fixed;
                object-fit: fill;
                /* display: flex;
                align-items: flex-end; */
            }
            .titleBubble {
                width: fit-content;
                padding-left: 40px;
                padding-right: 40px;
                padding-top: 20px;
                padding-bottom: 20px;
                background-color:#00000030;
                border-radius: 50px;
                color:white;
                font-size: 75px;
                font-weight:800;
                align-items: center;
                justify-content: center;
                font-family: 'Inter';
                backdrop-filter: blur(20px);
                z-index: 1;
                position: relative;
                margin: 20px auto 20px auto;
                /* filter: drop-shadow(5px 4px 2px #00000050); */
            }
            .titleText {
                text-shadow: 2px 2px 2px #00000050
            }
            .module {
                height: 400px;
                width: 33.33%;
                padding: 20px;
                text-align: center;
            }
            /* .test {
                outline-style: solid;
                outline-color: green;
                outline-width: 1px;
            }  */
            .label {
                font-size: 20px;
                font-weight: bold;
                color: #FFFFFF;
                text-shadow: 2px 2px 2px #00000050
            }

            .textarea {
                margin-top: 15px;
                width: 23vw;
                height: 335px;
                font-size: 16px;
                padding: 10px;
                resize: none;
                border-radius: 20px;
                border: none;
                filter: drop-shadow(2px 2px 2px #00000025);
            }
            .button {
                background-color: white;
                border: none;
                font-family: 'Inter';
                color: black;
                padding: 15px 32px;
                text-align: center;
                text-decoration: none;
                display: inline-block;
                font-size: 16px;
                margin: 4px 2px;
                cursor: pointer;
                border-radius: 10px;
                filter: drop-shadow(2px 2px 2px #00000025);
                font-weight: bold;
            }
            .button:hover {
                filter: none;
                background-color: #EBEBEB;
            }
            #footer {
            height: 50px; /* the footer's total height */
            text-align: center;
            }

            #footer-text {
            background-color: #f3e5f5;
            border: 0px solid #ab47bc;
            height: 20px; /* height + top/bottom paddding + top/bottom border must add up to footer height */
            padding: 20px;
            font-family: 'Inter';
            }
    </style>
</head>
<body>
    <div class="container test">
        <div class="headerContainer test">
            <div class="spectrum">
                <svg width=100vw height=151px viewBox="0 0 1436 180" preserveAspectRatio="none" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M959 180H479L654.5 -1H782.5L959 180Z" fill="#FED700"/>
                    <path d="M959 180H479L654.5 -1H782.5L959 180Z" fill="black" fill-opacity="0.2"/>
                    <path d="M526 -0.432602L0 180L478.5 180H479L654.5 -1L526 -0.432602Z" fill="#FE218B"/>
                    <path d="M526 -0.432602L0 180L478.5 180H479L654.5 -1L526 -0.432602Z" fill="black" fill-opacity="0.2"/>
                    <path d="M910.402 -1L1436 180H959.365L783 -1H910.402Z" fill="#21B0FE"/>
                    <path d="M910.402 -1L1436 180H959.365L783 -1H910.402Z" fill="black" fill-opacity="0.2"/>
                </svg>
            </div>
            <div class="titleBubble test">
                <div class="titleText test">
                    <span style="color:#FF8EC4;">MIX</span>
                    <span style="color:#FFE760;"> IT</span>
                    <span style="color:#9ADBFF;"> UP!</span>
                </div>
            </div>
        </div><%= form_with model: @recipe do |form| %>
    <div>
        <div class="inContainer test">
            <div style="background-color: #FE218B" class="module test">
                <%= form.label :ingredients, class: 'label'%><br>
                <%= form.text_area :ingredients, class: 'textarea', placeholder:"What do you have in your pantry? List with commas!" %>
            </div>
        <div style="background-color: #FED700" class="module test">
            <%= form.label :origin, class: 'label' %><br>
            <%= form.text_area :origin, class: 'textarea', placeholder: "Pick any nation from around the world!" %>
            </div>
            <div style="background-color: #21B0FE" class="module test">
            <p class="label">
                Try this out!
            </p>
            <%= form.submit class:"button"%>
            </div><%end %>
        </div>
        </div>
        <footer id="footer">
        <div id="footer-text">Built with ♥️ by <a href="https://www.linkedin.com/in/rachel-channell-9528a3215/" target="_blank"> Rachel</a>, <a href="https://www.linkedin.com/in/biashok" target="_blank"> Bia</a>, <a href="https://devpost.com/TaufeqRazakh" target="_blank"> Taufeq</a>, and <a href="https://joshuawolk.framer.website/" target="_blank"> Josh</a></div>
        </footer>
    </body>
</html>

app/views/recipes/show.html.erb
<!DOCTYPE html>
<html>
    <head>

    <style>
    p {
    margin: 10px 10px 10px 10px;
    }
    </style>
    <title>
        Mix It Up!
    </title>
    <link href='https://fonts.googleapis.com/css?family=Inter' rel='stylesheet'>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@800&amp;display=swap" rel="stylesheet">
    <style>
            body {
                background-image: linear-gradient(#000000,#CACACA,#FFFFFF);
                margin: 0px;
            }
            .container{
                display: inline-block;
                width: 100%;
                flex-direction: column;
            }
            .headerContainer {
                position: relative;
                align-items: center;
                justify-content: center;
            }
            .inContainer {
                display: flex;
                flex-direction: row;
                font-family: 'Inter';
            }
            .spectrum {
                width: 100%;
                z-index: -1;
                height: 15vw;
                position: fixed;
                /* display: flex;
                align-items: flex-end; */
            }
            .titleBubble {
                width: fit-content;
                padding-left: 40px;
                padding-right: 40px;
                padding-top: 20px;
                padding-bottom: 20px;
                background-color:#00000030;
                border-radius: 50px;
                color:white;
                font-size: 75px;
                font-weight:800;
                align-items: center;
                justify-content: center;
                font-family: 'Inter';
                backdrop-filter: blur(20px);
                z-index: 1;
                position: relative;
                margin: 20px auto 20px auto;
                /* filter: drop-shadow(5px 4px 2px #00000050); */
            }
            .titleText {
                text-shadow: 2px 2px 2px #00000050
            }
            .module {
                height: 400px;
                width: 33.33%;
                padding: 20px;
                text-align: center;
                overflow-y:scroll;
            }
            /* .test {
                outline-style: solid;
                outline-color: green;
                outline-width: 1px;
            } */
            .label {
                font-size: 20px;
                font-weight: bold;
                color: #FFFFFF;
                text-shadow: 2px 2px 2px #00000050
            }
            .text {
                font-size: 20px;
                font-weight: bold;
                color: #00000070;
            }

            .textarea {
                margin-top: 15px;
                width: 23vw;
                height: 335px;
                font-size: 16px;
                padding: 10px;
                resize: none;
                border-radius: 20px;
                filter: drop-shadow(2px 2px 2px #00000025);
            }

            .scroll {
              padding: 5px;
              font-family: 'Inter';
            }

            .button {
                background-color: white;
                border: none;
                font-family: 'Inter';
                color: black;
                padding: 15px 32px;
                text-align: center;
                text-decoration: none;
                display: inline-block;
                font-size: 16px;
                margin: 4px 2px;
                cursor: pointer;
                border-radius: 10px;
                filter: drop-shadow(2px 2px 2px #00000025);
                font-weight: bold;
            }
            .button:hover {
                filter: none;
                background-color: #EBEBEB;
            }

            #footer {
            height: 50px; /* the footer's total height */
            text-align: center;
            }

            #footer-text {
            background-color: #f3e5f5;
            border: 0px solid #ab47bc;
            height: 20px; /* height + top/bottom paddding + top/bottom border must add up to footer height */
            padding: 20px;
            font-family: 'Inter';
            }
          
    </style>
</head>
  <body>
    <div class="container test">
        <div class="headerContainer test">
            <div class="spectrum">
                <svg width=100vw height=151px viewBox="0 0 1436 180" preserveAspectRatio="none" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M959 180H479L654.5 -1H782.5L959 180Z" fill="#FED700"/>
                    <path d="M959 180H479L654.5 -1H782.5L959 180Z" fill="black" fill-opacity="0.2"/>
                    <path d="M526 -0.432602L0 180L478.5 179.433L654 -1L526 -0.432602Z" fill="#FE218B"/>
                    <path d="M526 -0.432602L0 180L478.5 179.433L654 -1L526 -0.432602Z" fill="black" fill-opacity="0.2"/>
                    <path d="M910.402 -1L1436 180H959.365L783 -1H910.402Z" fill="#21B0FE"/>
                    <path d="M910.402 -1L1436 180H959.365L783 -1H910.402Z" fill="black" fill-opacity="0.2"/>
                </svg>
            </div>
        <div class="titleBubble test">
            <div class="titleText test">
            <span style="color:#FF8EC4;">MIX</span>
            <span style="color:#FFE760;"> IT</span>
            <span style="color:#9ADBFF;"> UP!</span>
            </div>
        </div>
      </div>
      <div>
        <div class="inContainer test">
          <div style="background-color: #FE218B" class="module test">
            <p class="label">
              Ingredients
            </p>
            <div class="text">
              <%= @recipe.ingredients %>
            </div>
          </div>
          <div style="background-color: #FED700" class="module test">
            <p class="label">
              Origin
            </p>
            <div class="text">
              <%= @recipe.origin%>
            </div>
          </div>
          <div style="background-color: #21B0FE" class="module test">
            <p class="label">
              Try this out!
            </p>
            <div>
              <div class="text">
                <%= @recipe.title %>
              </div>
              <div class="scroll">
              <%= @recipe.requirements %>
              </div>
              <div class="scroll">
              <%= @recipe.instructions %>
              </div>
              <%= link_to "Try Again", new_recipe_url, class:'button'%>
          </div>
        </div>
      </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
        <footer id="footer">
        <div id="footer-text">Built with ♥️ by <a href="https://www.linkedin.com/in/rachel-channell-9528a3215/" target="_blank"> Rachel</a>, <a href="https://www.linkedin.com/in/biashok" target="_blank"> Bia</a>, <a href="https://devpost.com/TaufeqRazakh" target="_blank"> Taufeq</a>, and <a href="https://joshuawolk.framer.website/" target="_blank"> Josh</a></div>
        </footer>
  </body>
</html>